### PR TITLE
Show the current fold

### PR DESCRIPTION
**Pull request by MicheleBertoli**
I think it might be useful for the user to see his own fold, like this:
screen shot 2015-02-14 at 09 04 10

### CODE REVIEW

**Comment by iest** [comment]
Perfect!

One question: does it look better with their fold drawn first or last?

**Comment by MicheleBertoli** [comment]
Not sure I understood what you mean by "first or last" :)
Do you think it'd be better to swap these lines: https://github.com/iest/i-am-the-fold/pull/4/files#diff-50cfa59973c04321b5da0c6da0fdf4feR17?

**Comment by iest** [comment]
Yeah! I was wondering how it looked if it drew first vs last. Aka can you see it underneath all the others?

**Comment by MicheleBertoli** [comment]
As you can see, I assigned the [higher](https://github.com/iest/i-am-the-fold/pull/4/files#diff-dbe0876d6d2eb9f1d2b99bf53b34ece8R45) `z-index` to the `current` element.
In this way when you `hover` another element, you can see its value (the best solution from my point of view).

screen shot 2015-02-14 at 11 15 15

If I swap the two lines to render the `current` element last, you cannot see other element's values on `hover`.

screen shot 2015-02-14 at 11 14 03

**Comment by iest** [comment]
Live! http://www.iamthefold.com

**Pull request merged**
