### PR TITLE
Fix bug in measuring windows height.

### PR DESCRIPTION
**Pull request by milani**
We should use available height not the visible part of it.

### CODE REVIEW

**Comment by Garciat** [comment]
Isn't the visible portion the whole point of the experiment?

**Comment by iest** [comment]
I don't see how this changes anything? When are the numbers ever different?

**Comment by Garciat** [comment]
Numbers are different when the browser window is not maximized, I believe.

**Comment by iest** [comment]
[From stackoverflow](http://stackoverflow.com/questions/3044230/difference-between-screen-availheight-and-window-height):

> **window.innerHeight or $(window).height()**
> It's the height of the viewport that shows the website, just the content, no browser's bars.
> 
> **screen.availHeight**
> It's the height the browser's window can have if it is maximized, including the browser's bars. So when the window is maximized, screen.availHeight === window.outerHeight

We 100% want `window.innerHeight` (aka the size of the area of the viewable content). So I'm gonna close this one — but I appreciate the input!

**Pull request closed without merging**
